import Link from 'next/link';
import Image from 'next/image';
import {ArrowUpRight} from 'lucide-react';
import {Eyebrow} from '@/components/brand/editorial';
import {socials,brandLinks} from '@/lib/editorial';
import {absoluteUrl} from '@/lib/site';
import {pageMetadata} from '@/lib/page-metadata';
export const metadata=pageMetadata('Official Links & Resources','Find Sacco Financial on YouTube, TikTok, Instagram, Facebook, X, and Threads. Explore research and investing resources.','/link-tree');
export default function Links(){const schema={"@context":"https://schema.org","@type":"CollectionPage",name:"Sacco Financial Official Links",url:absoluteUrl("/link-tree")};return <main id="main-content" className="container link-hub"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="link-hub-intro"><Image src="/images/profile.jpg" alt="Justin Sacco" width={180} height={180} priority/><Eyebrow>Justin Sacco / Official links</Eyebrow><h1>FOLLOW<br/><span>THE CURIOSITY.</span></h1><p>Markets, individual stocks, and the work behind the perspective.</p></section><section className="hub-links" aria-label="Resources and social channels"><a className="hub-feature" href={brandLinks.free}><div><small>START HERE / FREE RESOURCE</small><h2>The free investing guide</h2></div><ArrowUpRight/></a><Link href="/premium"><div><small>THE RESEARCH LAYER</small><h2>Explore Sacco Premium</h2></div><ArrowUpRight/></Link><Link href="/financial-blueprint"><div><small>BUILD YOUR FOUNDATION</small><h2>Financial Base Blueprint</h2></div><ArrowUpRight/></Link><div className="hub-socials">{socials.map(([n,h])=><a href={h} key={n} target="_blank" rel="noopener noreferrer">{n}<ArrowUpRight size={18}/></a>)}<a href="https://x.com/justin_sacco" target="_blank" rel="noopener noreferrer">Justin on X<ArrowUpRight size={18}/></a></div><Link href="/media"><h2>Media &amp; market coverage</h2><ArrowUpRight/></Link></section></main>}
