import type {ResearchEvent} from './events';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderResearchEmail(event:ResearchEvent,origin:string,unsubscribe?:string){
 const base=new URL(origin);
 if(!['http:','https:'].includes(base.protocol)||base.username||base.password)throw new Error('INVALID_ORIGIN');
 if(!/^\/premium\/[a-z0-9/#-]+$/.test(event.path))throw new Error('INVALID_RESEARCH_PATH');
 const url=new URL(event.path,base.origin).href;
 const preferences=new URL('/premium/account#research-notifications',base.origin).href;
 if(unsubscribe){const link=new URL(unsubscribe);if(link.origin!==base.origin||link.pathname!=='/email/unsubscribe'||!/^\w{64}$/.test(link.searchParams.get('token')||''))throw new Error('INVALID_UNSUBSCRIBE_URL');}
 const text=['SACCO PREMIUM',event.label,event.headline,...event.details,event.summary,event.cta+': '+url,'Manage Email Preferences: '+preferences,unsubscribe?'Unsubscribe: '+unsubscribe:'','You opted into Premium research notifications. Turn these off in your Account. Account and billing emails are unaffected.'].filter(Boolean).join('\n\n');
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>${escape(event.subject)}</title></head><body style="margin:0;background:#11151b;color:#f3f4f6;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#1b222c;border-top:3px solid #68c5e8"><tr><td style="padding:28px 24px;overflow-wrap:anywhere"><p style="font-size:18px;font-weight:bold;letter-spacing:2px">SACCO PREMIUM</p><p style="font-size:12px;color:#8fd8f2;letter-spacing:2px;margin-top:32px">${escape(event.label)}</p><h1 style="font-size:28px;line-height:1.2">${escape(event.headline)}</h1>${event.details.map(d=>`<p style="color:#cbd5e1">${escape(d)}</p>`).join('')}${event.summary?`<p style="font-size:16px;line-height:1.7;white-space:pre-line">${escape(event.summary)}</p>`:''}<p style="margin:32px 0"><a href="${escape(url)}" style="display:inline-block;padding:16px 18px;background:#8fd8f2;color:#11151b;text-decoration:none;font-size:14px;font-weight:bold">${escape(event.cta)}</a></p><p style="font-size:13px;line-height:1.6;color:#cbd5e1">You opted into Premium research notifications. <a href="${escape(preferences)}" style="color:#8fd8f2">Manage Email Preferences</a> to turn them off. Account and billing emails are unaffected.${unsubscribe?` <a href="${escape(unsubscribe)}" style="color:#8fd8f2">Unsubscribe</a>`:''}</p></td></tr></table></td></tr></table></body></html>`;
 return {subject:event.subject,html,text,url,preferences,headers:unsubscribe?{'List-Unsubscribe':'<'+unsubscribe+'>','List-Unsubscribe-Post':'List-Unsubscribe=One-Click'}:undefined};
}
