import {LegacyDisclosure,WheelPositionSummary} from './wheel-position';
import TradeResult from './trade-result';
import {researchNumber} from './research-header';
import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import {premiumDate,type Opportunity} from '@/lib/premium-content';
import './opportunities.css';
export default function OpportunityCard({opportunity:o}:{opportunity:Opportunity}){
 return <article className="watch-card opportunity-card" data-status={o.tradeStatus}><div className="premium-research-id"><span>OPPORTUNITY {researchNumber(o.id)}</span><span>Updated {premiumDate(o.updatedAt)}</span></div><div className="watch-top"><span>{o.ticker}</span><span className="opportunity-status">Trade Status: {o.tradeStatus.toUpperCase()}</span></div><p className="opportunity-meta">{o.company} / {o.sector}{o.etfTickers?.length?` / ${o.etfTickers.join(', ')}`:''}</p>{o.positionOrigin==='Legacy'&&<LegacyDisclosure/>}<WheelPositionSummary opportunity={o}/>{o.riskUpdate&&<p className="opportunity-meta">STOP RAISED · ${o.riskUpdate.previousStop} → ${o.trade?.stopPrice}</p>}{o.nextCatalyst&&<p className="opportunity-meta">NEXT CATALYST · {o.nextCatalyst}</p>}<TradeResult opportunity={o}/><h3><Link href={`/premium/opportunities/${o.slug}`}>{o.title}</Link></h3><p>{o.summary||o.setupThesis}</p>{o.trade&&!o.wheel&&o.tradeStatus!=='Closed'&&<><dl className="opportunity-price-grid">{o.trade.entryPrice!==undefined&&<div><dt>Entry</dt><dd>${o.trade.entryPrice}</dd></div>}{o.trade.stopPrice!==undefined&&<div><dt>Stop</dt><dd>${o.trade.stopPrice}</dd></div>}{o.trade.firstTargetPrice!==undefined&&<div><dt>First target</dt><dd>${o.trade.firstTargetPrice}</dd></div>}</dl><p className="opportunity-meta">{o.trade.entryType==='accumulation'?'Position started':'Position opened'}: {premiumDate(o.trade.enteredAt)}{o.trade.quantity!==undefined&&<> · {o.trade.quantity} shares</>}</p></>}{o.preferredAddZone&&<p className="opportunity-meta">Preferred add / reassessment: {o.preferredAddZone} · Not yet filled</p>}{!o.trade&&o.tradeStatus==='Watching'&&<p className="opportunity-meta">No active position.</p>}{o.setupRange&&<p className="opportunity-meta">Range: {o.setupRange} · Preferred area: {o.entryFramework} · Breakout: {o.confirmation} · Setup invalidation: {o.riskInvalidation}</p>}<div className="opportunity-next"><span className="eyebrow">What needs to happen next?</span><p>{o.nextStepSummary||o.nextCondition}</p></div><p className="opportunity-meta">Technical Stage: {o.technicalStage||'Unassigned'} · Updated {premiumDate(o.updatedAt)}</p><Link className="text-link" href={`/premium/opportunities/${o.slug}`}>{o.tradeStatus==='Closed'?'Read the result & history':'Read the setup'} <ArrowRight size={16}/></Link></article>;
}
export function OpportunityEmptyState(){return <div className="opportunity-empty"><h3>No published opportunities yet.</h3><p>Reviewed Stage 2 setups will appear here after completing the Sacco Financial research framework.</p></div>;}
