import {premiumDate,type Opportunity} from '@/lib/premium-content';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'});
export function LegacyDisclosure(){return <aside className="legacy-disclosure"><span className="eyebrow">Legacy position · Pre-launch</span><p>This position was established before Sacco Premium launched. It was not originally published as a Premium trade. Historical trades are included for transparency and context; members can follow Justin’s management from this point forward.</p></aside>;}
export function WheelPositionSummary({opportunity:o}:{opportunity:Opportunity}){
 if(!o.wheel||!o.trade)return null;const call=o.wheel.fills.find(f=>f.id===o.wheel!.currentCallId);
 return <div className="wheel-summary"><span className="eyebrow">Wheel Strategy</span><dl><div><dt>Shares</dt><dd>{o.trade.quantity}</dd></div><div><dt>Broker share basis</dt><dd>{money(o.trade.entryPrice!)} / share</dd></div><div><dt>Current covered call</dt><dd>{call?`${money(call.strike)} strike · ${premiumDate(call.expiresAt)}`:'No documented open call'}</dd></div></dl></div>;
}
export default function WheelPositionDetails({opportunity:o}:{opportunity:Opportunity}){
 if(!o.wheel||!o.trade)return null;
 const gross=o.wheel.fills.reduce((sum,f)=>sum+Math.round(f.premiumPerShare*100)*f.multiplier*f.contracts,0)/100;
 return <section className="section opportunity-detail-section wheel-details" aria-label="Wheel position history"><h2>Ownership & Option History</h2><WheelPositionSummary opportunity={o}/><p>Total broker share basis: {money(o.trade.entryPrice!*o.trade.quantity!)}. Shares originated through put assignment; the exact assignment date is not supplied. Option premiums have not been deducted from the $45.00 broker share basis.</p><h3>Historical filled orders</h3><p>Transcribed from Justin’s supplied trade details. All three entries are sell-to-open fills. An opening credit is not necessarily final realized profit.</p><div className="wheel-table-scroll" tabIndex={0} role="region" aria-label="Filled option orders"><table className="wheel-history"><thead><tr><th>Date</th><th>Action / quantity</th><th>Contract / expiration</th><th>Premium per share</th><th>Gross received</th><th>Outcome</th></tr></thead><tbody>{o.wheel.fills.map(f=><tr key={f.id}><td>{premiumDate(f.filledAt)}</td><td>{f.action}<br/>{f.contracts} contract · {f.multiplier} shares</td><td>${f.strike} {f.optionType}<br/>{premiumDate(f.expiresAt)}</td><td>{money(f.premiumPerShare)}</td><td>{money(f.premiumPerShare*f.multiplier*f.contracts)}</td><td>{f.outcome==='Assigned'?'Assigned; exact date not supplied':f.outcome==='Open'?'Open — current covered call':'Closing / expiration outcome not verified'}</td></tr>)}</tbody></table></div><div className="opportunity-next"><span className="eyebrow">Gross option premium received</span><h3>{money(gross)}</h3><p>This is gross premium from the three documented opening fills, not realized profit. Final options P&amp;L depends on closing, assignment or expiration outcomes and applicable costs. The August call outcome is unverified; the October call remains open. No combined stock-and-options profit is reported.</p></div><h3>Personal ownership framework</h3><p>{o.wheel.ownershipFramework}</p><h3>Why the wheel / how it works</h3><p>{o.wheel.process}</p></section>;
}
