export { ReplitHeroSection } from "./HeroSection";
export { ReplitVideoSection } from "./VideoSection";
export { ReplitProblemSection } from "./ProblemSection";
export { ReplitSolutionSection } from "./SolutionSection";
export { ReplitWhatsInsideSection } from "./WhatsInsideSection";
export { ReplitTransformationSection } from "./TransformationSection";
export { ReplitTrustSection } from "./TrustSection";
export { ReplitFaqSection } from "./FaqSection";
export { ReplitFinalCtaSection } from "./FinalCtaSection";
