import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireAnalyticsAdmin} from '@/lib/analytics/admin';
import {googleReporting} from '@/lib/analytics/reporting';
import {operationsReporting} from '@/lib/analytics/operations';
import {milestoneLabels,reportingDays,type Report} from '@/lib/analytics/reporting-model';
import type {Reports} from '@/lib/analytics/reporting-client';
import './analytics.css';
export const dynamic='force-dynamic';
export const metadata={title:'Analytics | Sacco Premium',robots:{index:false,follow:false}};
const number=(value:number)=>new Intl.NumberFormat('en-US').format(value);
function Metric({label,value,note}:{label:string;value:number|undefined;note:string}){return <div className="analytics-metric"><span>{label}</span><strong>{value===undefined?'—':number(value)}</strong><small>{note}</small></div>;}
function ReportTable({report,headers}:{report:Report|null|undefined;headers:string[]}){
 if(!report)return <p className="analytics-empty">Report unavailable. No activity count is implied.</p>;
 if(!report.rows.length)return <p className="analytics-empty">No recorded activity in this period.</p>;
 return <><div className="analytics-table-scroll"><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{report.rows.map((row,i)=><tr key={i}>{row.dimensions.map((cell,j)=><td key={'d'+j}>{cell||'(not set)'}</td>)}{row.metrics.map((cell,j)=><td key={'m'+j}>{number(cell)}</td>)}</tr>)}</tbody></table></div>{report.limited&&<p className="analytics-note">Top rows shown; this table is not the full total.</p>}{report.qualified&&<p className="analytics-note">Google applied thresholding, sampling, or grouped data. These counts may be incomplete.</p>}</>;
}
export default async function Page({searchParams}:{searchParams:Promise<{days?:string}>}){
 try{await requireAnalyticsAdmin();}catch{notFound();}
 const days=reportingDays((await searchParams).days);
 const [google,operations]=await Promise.all([googleReporting(days),operationsReporting()]);
 const reports:Partial<Reports>='reports' in google?google.reports:{};
 const summary=reports.overview?.rows[0]?.metrics;
 const count=(i:number)=>reports.overview?(summary?.[i]||0):undefined;
 const member=operations.members;
 const eventRows=reports.milestones?.rows||[];
 const events=reports.milestones?{...reports.milestones,rows:Object.entries(milestoneLabels).map(([name,label])=>({dimensions:[label],metrics:eventRows.find(row=>row.dimensions[0]===name)?.metrics||[0,0]}))}:null;
 const daily=reports.daily;
 const maxSessions=Math.max(1,...(daily?.rows.map(row=>row.metrics[0])||[]));
 return <main className="container analytics-admin">
  <header className="analytics-header"><div><p className="analytics-eyebrow">SACCO PREMIUM / ADMINISTRATOR</p><h1>Analytics</h1><p>Understand how people find Sacco, join Premium, and use the research.</p></div><nav aria-label="Admin navigation"><Link href="/premium/admin/notifications">Email notifications</Link><Link href="/premium/account">Account</Link></nav></header>
  <div className="analytics-toolbar"><div><span className="analytics-status">{operations.local?'LOCAL DATABASE · GOOGLE DISCONNECTED':google.status==='ready'?'GOOGLE REPORTS CONNECTED':'GOOGLE REPORTS NOT CONNECTED'}</span><p>Website reports cover completed days through yesterday, in the GA property time zone.</p></div><form method="get"><label htmlFor="analytics-days">Website period</label><select id="analytics-days" name="days" defaultValue={days}><option value="7">Last 7 days</option><option value="28">Last 28 days</option><option value="90">Last 90 days</option></select><button className="button" type="submit">Apply</button></form></div>
  {google.status!=='ready'&&<aside className="analytics-notice"><strong>{google.status==='local'?'Your local preview is isolated.':google.status==='unconfigured'?'Google reporting needs configuration.':'Google reports could not be loaded.'}</strong><p>{google.status==='local'?'Membership and email records below come from your local test database. Local browser events stay in the preview log and do not populate Google reports.':'Check GA_PROPERTY_ID, the GOOGLE_ANALYTICS_SERVICE_ACCOUNT_JSON entry in the billing secret, Google Analytics Data API access, and the service account’s Viewer access to this property. Reports retry after the five-minute cache expires.'}</p></aside>}
  <section aria-labelledby="website-heading"><div className="analytics-section-title"><h2 id="website-heading">Website activity</h2><span>Last {days} completed days</span></div><div className="analytics-metrics"><Metric label="Tracked users" value={count(0)} note="GA users, not member accounts"/><Metric label="Sessions" value={count(1)} note="Visits recorded by Google"/><Metric label="Page views" value={count(2)} note="Repeat views included"/><Metric label="Paid checkouts" value={count(3)} note="Tracked initial purchases"/></div><p className="analytics-note">Opt-in tracking is a subset of your audience. Blockers, consent choices, and Google processing delays affect counts. Stripe remains the payment source of truth. Reports are cached for five minutes.</p>{reports.overview?.qualified&&<p className="analytics-note">Google qualified the overview with thresholding, sampling, or grouped data.</p>}</section>
  <section className="analytics-panel"><h2>Visits over time</h2><p>Sessions per day. Missing days have no row in Google’s response.</p>{daily?.rows.length?<><div className="analytics-daily" role="img" aria-label="Daily session bars; exact values are in the table below">{daily.rows.map(row=><div key={row.dimensions[0]} title={`${row.dimensions[0]}: ${row.metrics[0]} sessions`}><span style={{height:`${Math.max(2,row.metrics[0]/maxSessions*100)}%`}}/></div>)}</div><details><summary>View daily counts</summary><ReportTable report={daily} headers={['Date (YYYYMMDD)','Sessions']}/></details></>:<ReportTable report={daily} headers={['Date','Sessions']}/>}</section>
  <div className="analytics-grid"><section className="analytics-panel"><h2>Where visits come from</h2><p>Session source and medium, with purchases attributed by Google. Use tagged bio links to identify each platform.</p><ReportTable report={reports.sources} headers={['Source','Medium','Sessions','Purchases']}/></section><section className="analytics-panel"><h2>Journey activity</h2><p>Independent event totals, not a sequential conversion funnel. A checkout request does not confirm that Stripe loaded.</p><ReportTable report={events} headers={['Action','Events','Users']}/></section></div>
  <div className="analytics-grid"><section className="analytics-panel"><h2>Research people open</h2><p>Most-viewed Outlook and Opportunity pages. Repeat views count; engaged reading is reported separately above.</p><ReportTable report={reports.content} headers={['Research page','Views','Users']}/></section><section className="analytics-panel"><h2>Devices</h2><p>Use this mix to prioritize mobile and desktop testing.</p><ReportTable report={reports.devices} headers={['Device','Sessions']}/></section></div>
  <section aria-labelledby="members-heading"><div className="analytics-section-title"><h2 id="members-heading">Membership health</h2><span>Current database snapshot · {operations.local?'test':'live'} billing</span></div><div className="analytics-metrics"><Metric label="Members with access" value={member?.members} note="Unique paid or manual members"/><Metric label="Paid members" value={member?.paidMembers} note="Includes valid payment grace"/><Metric label="Scheduled to cancel" value={member?.canceling} note="Subscriptions with access remaining"/><Metric label="Past-due subscriptions" value={member?.pastDue} note="Includes expired grace periods"/></div>{!member&&<p className="analytics-note">Membership records unavailable. No zero counts are assumed.</p>}<p className="analytics-note">This is today’s access state, independent of the website date filter. Scheduled cancellations are not a historical churn rate.</p></section>
  <section className="analytics-panel"><div className="analytics-section-title"><h2>Email preferences</h2><Link href="/premium/admin/notifications">Manage notifications →</Link></div><p>Saved choices among members who currently have access.</p><div className="analytics-preferences"><Metric label="Notifications ON" value={member?.on} note="Saved opt-in"/><Metric label="Notifications OFF" value={member?.off} note="Saved opt-out"/><Metric label="No saved preference" value={member?.unset} note="Not opted in"/></div><p className="analytics-note">ON is not the sendable audience: suppression, verified email, and any test-recipient restriction also apply. Preview a notification to see its eligible recipients.</p></section>
  <section className="analytics-panel"><h2>Recent research notifications</h2><p>Latest 10 {operations.local?'dry-run':'live'} notification records, independent of the website date filter. “Accepted” means the provider accepted the send; it does not confirm delivery.</p>{operations.email===null?<p className="analytics-empty">Email log unavailable.</p>:!operations.email.length?<p className="analytics-empty">No {operations.local?'dry-run':'live'} notifications recorded yet.</p>:<div className="analytics-table-scroll"><table><thead><tr><th scope="col">Subject</th><th scope="col">Status</th><th scope="col">Intended recipients</th><th scope="col">Date (UTC)</th></tr></thead><tbody>{operations.email.map(row=><tr key={row.id}><td>{row.subject}</td><td>{row.status==='sent'?'Accepted':row.status.replaceAll('_',' ')}</td><td>{number(row.recipient_count)}</td><td>{new Date(row.created_at).toISOString().slice(0,10)}</td></tr>)}</tbody></table></div>}<p className="analytics-note">Email delivery, open, and click counts are not collected in this dashboard yet. Opens alone would not prove a person read an email.</p></section>
  <footer className="analytics-note">Admin-only reporting. No email addresses or payment details are included. {'checkedAt' in google?`Google reports checked ${new Date(google.checkedAt).toISOString().replace('T',' ').slice(0,16)} UTC.`:''}</footer>
 </main>;
}
