import {requirePremium} from '@/lib/premium-access';
import PremiumNavigation from '@/components/premium/navigation';
import {Eyebrow,SectionHeader} from '@/components/brand/editorial';
import {weeklyOutlooks} from '@/lib/premium-opportunities';
import {premiumDate} from '@/lib/premium-content';
import {pageMetadata} from '@/lib/page-metadata';
export const metadata=pageMetadata('Weekly Outlook','Justin’s market thesis, what changes the view, and the game plan.','/premium/weekly-outlook',true);
export default async function Page(){
 await requirePremium();const outlook=weeklyOutlooks.filter(o=>o.publicationState==='published').sort((a,b)=>b.weekOf.localeCompare(a.weekOf))[0];
 return <main id="main-content" className="container"><PremiumNavigation/><section className="page-hero"><Eyebrow>Sacco Premium / Weekly Outlook</Eyebrow><h1>{outlook.title}</h1><p>Week of {premiumDate(outlook.weekOf)} · Sunday perspective: {premiumDate(outlook.perspectiveDate!)} · Published {premiumDate(outlook.publishedAt)}</p><p>{outlook.summary}</p></section>{[['Market context',outlook.marketContext],['What history tells us',outlook.historicalContext],['What changes my view',outlook.thesisChanges],['Areas of focus',outlook.sectorFocus]].map(([title,body])=><section className="section" key={title}><SectionHeader title={title!}/><div style={{maxWidth:850,display:'grid',gap:20}}>{body?.split('\n\n').map(p=><p key={p}>{p}</p>)}</div></section>)}<section className="section"><SectionHeader title="The week’s main events"/><div className="property-grid">{outlook.events?.map(e=><article key={e.day}><Eyebrow>{e.day}</Eyebrow><h3>{e.title}</h3><p>{e.description}</p></article>)}</div></section><section className="section"><SectionHeader title="The closing game plan"/><div style={{maxWidth:850,display:'grid',gap:20}}>{outlook.gamePlan.split('\n\n').map(p=><p key={p}>{p}</p>)}</div></section><section className="section"><p>Educational and informational research, not personalized investment advice. Past performance does not guarantee future results. Investing involves risk, including loss of principal.</p><details style={{marginTop:24}}><summary>Calendar and historical data references</summary><div className="actions">{outlook.sources?.map(s=><a className="text-link" key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.label}</a>)}</div></details></section></main>;
}
