import Link from 'next/link';
import Image from 'next/image';
import {ArrowUpRight,ArrowRight,Play,AudioLines} from 'lucide-react';
import {brandLinks,socials,type Story} from '@/lib/editorial';
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
export function AssetSlot({label,shape='video'}:{label:string;shape?:'video'|'portrait'}){return <div className={`asset-slot asset-${shape}`} role="img" aria-label={`Image placeholder: ${label}`}><span className="asset-cross" aria-hidden="true">+</span><span>{label}</span><small>IMAGE TO COME / {shape==='portrait'?'4:5':'16:9'}</small></div>}
export function SectionHeader({label,title,href,linkText='Explore'}:{label?:string;title:string;href?:string;linkText?:string}){return <div className="section-heading"><div>{label&&<Eyebrow>{label}</Eyebrow>}<h2>{title}</h2></div>{href&&<Link href={href} className="text-link">{linkText}<ArrowUpRight size={18}/></Link>}</div>}
export function StoryCard({story,compact=false}:{story:Story;compact?:boolean}){return <article className={`story-card ${compact?'compact-story':''}`}><a href={story.href} target="_blank" rel="noopener noreferrer" className="story-image-link" aria-label={story.title}>{story.image?<Image src={story.image} alt="" width={1024} height={576} sizes="(max-width: 600px) 100vw, 33vw"/>:<AssetSlot label={story.asset}/>}{story.kind==='video'&&<span className="play-badge"><Play size={18} fill="currentColor"/> Watch</span>}</a><div className="story-meta"><span>{story.category}</span>{story.date&&<time dateTime={story.dateTime}>{story.date}</time>}</div><h3><a href={story.href} target="_blank" rel="noopener noreferrer">{story.title}</a></h3><p>{story.description}</p><a href={story.href} target="_blank" rel="noopener noreferrer" className="text-link">{story.kind==='video'?'Watch':'Read'} on {story.outlet}<ArrowUpRight size={16}/></a></article>}
export function OutlookFeature(){return <section id="outlook" className="section"><SectionHeader label="The weekly perspective" title="The Market Outlook."/><div className="outlook-feature"><a className="outlook-thumbnail" href={brandLinks.marketOutlook} target="_blank" rel="noopener noreferrer" aria-label="Watch the Weekly Market Outlook series on YouTube"><Image src="/images/weekly-market-outlook.jpg" alt="Sacco Financial Market Outlook Series — drops every Sunday" width={1024} height={576} sizes="(max-width: 600px) 100vw, 55vw"/><span className="play-badge"><Play size={18} fill="currentColor"/> Watch</span></a><div className="outlook-copy"><Eyebrow>Weekly Market Outlook</Eyebrow><h3>The week ahead.<br/>Through an investor’s eyes.</h3><p>Stocks, catalysts, and the market narratives Justin is investigating. Start with the outlook, then follow the ideas into the research.</p><a className="button" href={brandLinks.marketOutlook} target="_blank" rel="noopener noreferrer"><Play size={16}/> Watch on YouTube</a></div></div></section>}
export function PremiumPreview({large=false}:{large?:boolean}){return <Link className={`publication-preview ${large?'publication-large':''}`} href="/premium/issue-001" aria-label="Read the Issue 001 prototype"><div className="publication-top"><span>SACCO <b>PREMIUM</b></span><span>ISSUE 001</span></div><p className="publication-date">THE WEEKLY BRIEF / SEP 14–18, 2026</p><h3>TURBULENCE.<br/>PATIENCE.<br/><span>OPPORTUNITY.</span></h3><p>I’m preparing for a rough week.<br/>I’m also preparing to buy.</p><div className="publication-bottom"><span>Market view / Watchlist / Opportunity Radar</span><ArrowUpRight/></div><span className="preview-label">ACTUAL ISSUE · PROTOTYPE</span></Link>}
export function PremiumBand(){return <section className="premium-band section"><div><Eyebrow>The research behind the story</Eyebrow><h2>Go beyond<br/>the headline.</h2><p>The market view. The watchlist. The conditions that would change my mind. Follow the thinking behind the ideas in Sacco Premium.</p><Link className="button" href="/premium">Explore Sacco Premium <ArrowUpRight size={18}/></Link><span className="support-note">Read the first issue · Prototype preview</span></div><PremiumPreview/></section>}
export function CreatorBio(){return <section id="about" className="section creator-bio"><div className="creator-image"><Image src="/images/headshot.jpg" alt="Justin Sacco, founder of Sacco Financial" width={1200} height={900} sizes="(max-width: 700px) 100vw, 45vw"/><span>JUSTIN SACCO / FOUNDER</span></div><div><Eyebrow>The person behind the perspective</Eyebrow><h2>I found something<br/>interesting.<br/><span className="muted-title">Come look at it<br/>with me.</span></h2><p>I’m Justin Sacco. My background in banking and financial services informs how I look at money. Sacco Financial is where I investigate markets, challenge investment ideas, and bring you into that process.</p><Link className="text-link" href="/about">Meet Justin <ArrowUpRight size={18}/></Link></div></section>}
export function NewsletterCTA(){return <section className="newsletter-section"><div><Eyebrow>Start with the fundamentals</Eyebrow><h2>A stronger base.<br/>A clearer next step.</h2><p>Get the free investing guide and join the Sacco Financial email list.</p></div><a className="button" href={brandLinks.free} target="_blank" rel="noopener noreferrer">Get the free guide <ArrowRight size={18}/></a></section>}
export function SocialProof(){return <section id="links" className="social-proof"><p className="eyebrow">Find Sacco Financial across your feed</p><div>{socials.slice(0,5).map(([name,href])=><a key={name} href={href} target="_blank" rel="noopener noreferrer">{name}<ArrowUpRight size={16}/></a>)}</div></section>}
export function SiteFooter(){return <footer className="brand-footer"><div className="container footer-grid"><div><Link href="/" className="wordmark">SACCO<span>FINANCIAL</span></Link><p>Markets. Individual stocks.<br/>A point of view worth investigating.</p><span className="footer-signoff"><AudioLines size={18}/> FINANCIAL MEDIA BY JUSTIN SACCO</span></div><div><h2>Explore</h2>{[['Media','/media'],['Research','/research'],['Premium','/premium'],['About','/about']].map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><h2>Resources</h2><Link href="/financial-blueprint">Financial Base Blueprint</Link><a href={brandLinks.free}>Free investing guide</a><Link href="/link-tree">Socials &amp; links</Link><Link href="/contact">Contact &amp; press</Link></div><div><h2>Follow along</h2>{socials.map(([n,h])=><a key={n} href={h} target="_blank" rel="noopener noreferrer">{n}<ArrowUpRight size={13}/></a>)}</div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} Sacco Financial</p><div><Link href="/disclosures">Disclosures</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><p className="footer-disclaimer">For educational and informational purposes. Not personalized investment advice. Investing involves risk, including loss of principal.</p></div></footer>}
